"""empty message

Revision ID: 967a4f14b7fa
Revises: 
Create Date: 2023-08-29 11:46:46.150789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967a4f14b7fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('physics', sa.Integer(), nullable=True),
    sa.Column('maths', sa.Integer(), nullable=True),
    sa.Column('english', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_name'))

    op.drop_table('student')
    # ### end Alembic commands ###
